### PR TITLE
Remove unnecessary files for Eidos reading

### PR DESCRIPTION
**Pull request by bgyori**
It occurred to me that a trivial way to shave ~2-3GB off this image is to remove other readers. If we're desperate, we can probably find more removables.

### CODE REVIEW

**Comment by bgyori** [comment]
@pagreene I added `--squash` to the docker build command in buildspec.yml. If this works on Codebuild (I haven't tried it there yet), the image should decrease in size. Can we test this?

**Comment by pagreene** [comment]
I just started a build. I also added a couple of commits I had to this PR, as they were also dockerfile related.

**Comment by bgyori** [comment]
@pagreene I was trying to look at the codebuild logs and interestingly, found that all of the builds were done on bigmech/indra-db/eidos-dockerfile/eidos.zip which is something I uploaded to S3 4/15. There is also a bigmech/indra-db/eidos-dockerfile/eidos-autogen.zip file but that was not used in any of the codebuild builds. This could explain why the builds remained the same size despite our expectation that they would become smaller. In light of this, what should we do with the build and this PR?

**Comment by pagreene** [comment]
@bgyori Oh, interesting. That could explain a lot. My first thought is we should fix the setting on AWS, try the build as it is on this PR, and see if that works any better.

**Comment by pagreene** [comment]
The eidos docker image built from this branch seems to be working fairly well, so we could merge this branch.

**Pull request merged**
